name: QuickSight Dashboard Migration

on:
  workflow_dispatch:
    inputs:
      dashboard_id:
        description: 'QuickSight Dashboard ID to promote (e.g., dev-dashboard-123)'
        required: true
        type: string
      promotion_environment:
        description: 'Select the promotion environment'
        required: true
        type: choice
        options:
          - 'DEV to QA'
          - 'QA to STAGE'
          - 'STAGE to PROD'

jobs:
  migrate_quicksight_dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests

      - name: Determine AWS Account IDs and Dashboard Mappings
        id: set_migration_parameters
        run: |
          case "${{ inputs.promotion_environment }}" in
            "DEV to QA")
              echo "source_account_id=11111" >> "$GITHUB_OUTPUT"
              echo "target_account_id=22222" >> "$GITHUB_OUTPUT"
              echo "old_account_id_generic=470822489487" >> "$GITHUB_OUTPUT" # Placeholder for generic DEV account ID
              echo "new_account_id_generic=470822489488" >> "$GITHUB_OUTPUT" # Placeholder for generic QA account ID
              # Specific Dashboard ID replacements for DEV to QA
              echo "dashboard_replacements={\"3519323f-3db4-4585-a0c1-a1df2698e3e0\": \"221553ff-d80a-4861-8890-ae7e028016b7\", \"bb9c4023-1f25-472b-bf31-7a8ded7c2c69\": \"8955b0d0-ee47-4915-aac4-c4f9dffa6821\", \"7d86f2f9-5bdf-402d-8d47-d7ab76bbaf87\": \"52825973-e237-4adb-8fe8-015c046066b4\"}" >> "$GITHUB_OUTPUT"
              ;;
            "QA to STAGE")
              echo "source_account_id=22222" >> "$GITHUB_OUTPUT"
              echo "target_account_id=33333" >> "$GITHUB_OUTPUT"
              echo "old_account_id_generic=470822489488" >> "$GITHUB_OUTPUT" # Placeholder for generic QA account ID
              echo "new_account_id_generic=470822489489" >> "$GITHUB_OUTPUT" # Placeholder for generic STAGE account ID
              # Specific Dashboard ID replacements for QA to STAGE
              echo "dashboard_replacements={\"qa-dashboard-id-1\": \"stage-dashboard-id-1\", \"qa-dashboard-id-2\": \"stage-dashboard-id-2\"}" >> "$GITHUB_OUTPUT"
              ;;
            "STAGE to PROD")
              echo "source_account_id=33333" >> "$GITHUB_OUTPUT"
              echo "target_account_id=44444" >> "$GITHUB_OUTPUT"
              echo "old_account_id_generic=470822489489" >> "$GITHUB_OUTPUT" # Placeholder for generic STAGE account ID
              echo "new_account_id_generic=470822489490" >> "$GITHUB_OUTPUT" # Placeholder for generic PROD account ID
              # Specific Dashboard ID replacements for STAGE to PROD
              echo "dashboard_replacements={\"stage-dashboard-id-a\": \"prod-dashboard-id-a\", \"stage-dashboard-id-b\": \"prod-dashboard-id-b\"}" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Invalid promotion environment selected."
              exit 1
              ;;
          esac

      - name: Configure AWS Credentials and Config Files
        shell: bash
        run: |
          mkdir -p ~/.aws
          echo "[source]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.SOURCE_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.SOURCE_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[profile source]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "" >> ~/.aws/credentials
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.TARGET_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.TARGET_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "" >> ~/.aws/config
          echo "[profile default]" >> ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config

      - name: Run QuickSight Migration Python Script
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python export_quicksight_dashboard.py --export-and-import \
            --source-account-id "${{ steps.set_migration_parameters.outputs.source_account_id }}" \
            --source-profile "source" \
            --dashboard-id "${{ inputs.dashboard_id }}" \
            --source-aws-region "us-east-1" \
            --output-file-base "./quicksight_migration_output" \
            --target-account-id "${{ steps.set_migration_parameters.outputs.target_account_id }}" \
            --target-profile "default" \
            --target-aws-region "us-east-1" \
            --promotion-type "${{ inputs.promotion_environment }}" \
            --dashboard-replacements-json "${{ steps.set_migration_parameters.outputs.dashboard_replacements }}" \
            --old-account-id-generic "${{ steps.set_migration_parameters.outputs.old_account_id_generic }}" \
            --new-account-id-generic "${{ steps.set_migration_parameters.outputs.new_account_id_generic }}"
