name: QuickSight Dashboard Migration

on:
  workflow_dispatch:
    inputs:
      dashboard_id:
        description: 'QuickSight Dashboard ID to promote'
        required: true
        type: string
      promotion_environment:
        description: 'Select the promotion environment'
        required: true
        type: choice
        options:
          - 'DEV to QA'
          - 'QA to STAGE'
          - 'STAGE to PROD'

jobs:
  migrate_quicksight_dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests

      - name: Determine AWS Account IDs
        id: set_account_ids
        run: |
          case "${{ inputs.promotion_environment }}" in
            "DEV to QA")
              echo "source_account_id=11111" >> "$GITHUB_OUTPUT"
              echo "target_account_id=22222" >> "$GITHUB_OUTPUT"
              ;;
            "QA to STAGE")
              echo "source_account_id=22222" >> "$GITHUB_OUTPUT"
              echo "target_account_id=33333" >> "$GITHUB_OUTPUT"
              ;;
            "STAGE to PROD")
              echo "source_account_id=33333" >> "$GITHUB_OUTPUT"
              echo "target_account_id=44444" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Invalid promotion environment selected."
              exit 1
              ;;
          esac

      - name: Configure AWS Credentials and Config Files
        shell: bash
        run: |
          mkdir -p ~/.aws
          echo "[source]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.SOURCE_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.SOURCE_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[profile source]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "" >> ~/.aws/credentials
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.TARGET_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.TARGET_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "" >> ~/.aws/config
          echo "[profile default]" >> ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config

      - name: Run QuickSight Migration Python Script
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python export_quicksight_dashboard.py --export-and-import \
            --source-account-id "${{ steps.set_account_ids.outputs.source_account_id }}" \
            --source-profile "source" \
            --dashboard-id "${{ inputs.dashboard_id }}" \
            --source-aws-region "us-east-1" \
            --output-file-base "./quicksight_migration_output" \
            --target-account-id "${{ steps.set_account_ids.outputs.target_account_id }}" \
            --target-profile "default" \
            --target-aws-region "us-east-1" \
            --promotion-type "${{ inputs.promotion_environment }}" # CORRECTED: Changed to --promotion-type
