name: Multi-Account Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is needed for OIDC auth with AWS
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 urllib3
      
      - name: Create tmp directory
        run: mkdir -p ./tmp
      
      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::470822489487:role/quicksightpoc-trustrole
          aws-region: us-east-1
          role-session-name: GitHubDeploymentSession
      
      - name: Build in dev environment
        run: python folderexport.py --account-id 470822489487 --region us-east-1 --folder-id f286a908-ed92-4b89-ad22-af4c2a0b54b3 --output ./tmp/QuickSightBundle.zip
      
      - name: Upload QuickSight bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: quicksight-bundle
          path: ./tmp/QuickSightBundle.zip
          retention-days: 5

  import-qa:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read  # No OIDC permissions needed for this job
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 urllib3 awscli
      
      - name: Create tmp directory
        run: mkdir -p ./tmp
      
      - name: Download QuickSight bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: quicksight-bundle
          path: ./tmp

      # Using AWS access keys from secrets for QA
      - name: Configure AWS credentials for QA using access keys
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Debug AWS identity
        run: aws sts get-caller-identity
      
      - name: Import in QA environment
        run: python awscodeimport.py --file ./tmp/QuickSightBundle.zip --account-id 269801428807 --region us-east-1
