name: Multi-Account Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add global permissions that apply to all jobs
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 urllib3
      
      - name: Create tmp directory
        run: mkdir -p ./tmp
      
      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::470822489487:role/quicksightpoc-trustrole
          aws-region: us-east-1
          role-session-name: GitHubDeploymentSession
          audience: sts.amazonaws.com
      
      - name: Build in dev environment
        run: python folderexport.py --account-id 470822489487 --region us-east-1 --folder-id f286a908-ed92-4b89-ad22-af4c2a0b54b3 --output ./tmp/QuickSightBundle.zip
      
      - name: Upload QuickSight bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: quicksight-bundle
          path: ./tmp/QuickSightBundle.zip
          retention-days: 5

  import-qa:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 urllib3
      
      - name: Create tmp directory
        run: mkdir -p ./tmp
      
      - name: Download QuickSight bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: quicksight-bundle
          path: ./tmp

      - name: Configure AWS credentials for QA
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::269801428807:role/quicksightpoc-trustrole
          aws-region: us-east-1
          role-session-name: GitHubDeploymentSession
          audience: sts.amazonaws.com
      
      - name: Import in QA environment
        run: python awscodeimport.py --file ./tmp/QuickSightBundle.zip --account-id 269801428807 --region us-east-1
