name: Multi-Account Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is needed for OIDC auth with AWS
      contents: read
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 urllib3
      
      - name: Create tmp directory
        run: mkdir -p ./tmp
      
      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::470822489487:role/quicksightpoc-trustrole
          aws-region: us-east-1
          role-session-name: GitHubDeploymentSession
      
      - name: Build in dev environment
        run: python folderexport.py --account-id 470822489487 --region us-east-1 --folder-id f286a908-ed92-4b89-ad22-af4c2a0b54b3 --output ./tmp/QuickSightBundle.zip
      
      - name: Process QuickSight Bundle
        run: |
          # Create temporary directories for processing
          mkdir -p ./tmp/process_dir
          mkdir -p ./tmp/nested_process
          
          # Extract the main zip file
          unzip -q ./tmp/QuickSightBundle.zip -d ./tmp/process_dir
          
          # Function to recursively process all zip files and JSON files
          process_directory() {
            local dir=$1
            
            # Process all text files (including JSON) in this directory
            # The -type f finds all regular files regardless of extension
            find "$dir" -type f | while read file; do
              # Check if it's a text file using the file command
              if file "$file" | grep -q "text"; then
                sed -i \
                  -e 's/347f0c50-33a1-4fd2-bdd5-6f8867a05601/1e39287a-aafe-48a8-a81d-7d8e25a93c4f/g' \
                  -e 's/3519323f-3db4-4585-a0c1-a1df2698e3e0/221553ff-d80a-4861-8890-ae7e028016b7/g' \
                  -e 's/bb9c4023-1f25-472b-bf31-7a8ded7c2c69/52825973-e237-4adb-8fe8-015c046066b4/g' \
                  -e 's/bb9c4023-1f25-472b-bf31-7a8ded7c2c69/8955b0d0-ee47-4915-aac4-c4f9dffa6821/g' \
                  -e 's/7d86f2f9-5bdf-402d-8d47-d7ab76bbaf87/52825973-e237-4adb-8fe8-015c046066b4/g' \
                  -e 's/-dev-/-tst-/g' \
                  "$file"
              fi
            done
            
            # Find and process all nested zip files
            find "$dir" -name "*.zip" -type f | while read zip_file; do
              echo "Processing nested zip file: $zip_file"
              
              # Create a unique directory for this nested zip
              nested_dir="./tmp/nested_process/$(basename "$zip_file" .zip)"
              mkdir -p "$nested_dir"
              
              # Extract the nested zip
              unzip -q "$zip_file" -d "$nested_dir"
              
              # Process the extracted contents recursively
              process_directory "$nested_dir"
              
              # Re-zip the processed contents
              original_dir=$(pwd)
              cd "$nested_dir"
              rm -f "$zip_file"  # Remove the original zip file
              zip -q -r "$zip_file" *  # Create new zip with processed contents
              cd "$original_dir"
              
              # Replace the original zip file with the processed one
              mv "$nested_dir/$zip_file" "$zip_file"
              
              # Clean up the temporary nested directory
              rm -rf "$nested_dir"
            done
          }
          
          # Start processing from the root extraction directory
          process_directory "./tmp/process_dir"
          
          # Re-create the main zip file with all processed content
          cd ./tmp/process_dir
          rm -f ../QuickSightBundle.zip  # Remove the original zip file
          zip -q -r ../QuickSightBundle.zip *  # Create new zip with all processed contents
          cd ../../
          
          # Cleanup temporary directories
          rm -rf ./tmp/process_dir ./tmp/nested_process
      
      - name: Upload QuickSight bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: quicksight-bundle
          path: ./tmp/QuickSightBundle.zip
          retention-days: 5
  import-qa:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read  # No OIDC permissions needed for this job
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 urllib3 awscli
      
      - name: Create tmp directory
        run: mkdir -p ./tmp
      
      - name: Download QuickSight bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: quicksight-bundle
          path: ./tmp
      # Using AWS access keys from secrets for QA
      - name: Configure AWS credentials for QA using access keys
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Debug AWS identity
        run: aws sts get-caller-identity
      
      - name: Import in QA environment
        run: python folderimport.py --file ./tmp/QuickSightBundle.zip --account-id 269801428807 --region us-east-1
